#!/bin/bash

#for debugging
#set -ex

while read oldrev newrev ref
do
        # only checking out the master (or whatever branch you would like to deploy)
        if [ "$ref" = "refs/heads/$BRANCH" ];
        then
                echo "Ref $ref received. Deploying ${BRANCH} branch on server..."
                git --work-tree="$WORKING_DIR" --git-dir="$WORKING_DIR/.git" checkout -f $BRANCH
                sudo systemctl restart $PROJECT_NAME
        else
                echo "Ref $ref received. Doing nothing: only the $BRANCH branch may be deployed on this server."
        fi
done
